services:
  nginx:
    image: nginx:1.29.1-alpine-slim
    ports:
      - 80:80
    volumes:
      - ./application:/var/www/html
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    depends_on:
      - php
    container_name: nginx-container
    restart: on-failure:3

  php:
    build:
      context: .
      dockerfile: build/php/Dockerfile
    volumes:
      - ./application:/var/www/html
    networks:
      - default
    container_name: php-container
    restart: on-failure:3

networks:
  default:
    name: nphpnet
    driver: bridge
